#!/usr/bin/env python
# @generated by pegen from src/pegen/metagrammar_v2.gram

from typing import Any, Optional
from pegen.parser_v2 import (memoize, memoize_left_rec, logger,
                             DefaultParser, CharBasedParser, RuleResult, RuleResultValue,
                             success, failure)
#from pegen.parser_v2_old import memoize, memoize_left_rec, logger, DefaultParser, CharBasedParser #type:ignore
from ast import literal_eval
from typing import List, Union
import token
import tokenize
from tokenize import TokenInfo

from pegen.grammar_v2 import (
    Alt,
    #Action,
    GrammarItem,
    Cut,
    ExternDecl,
    Forced,
    Gather,
    Group,
    Item,
    Lookahead,
    LookaheadOrCut,
    MetaTuple,
    NameLeaf,
    TopLevelItem,
    NegativeLookahead,
    Opt,
    Plain,
    PositiveLookahead,
    Repeat0,
    Repeat1,
    Rhs,
    Rule,
    RuleName,
    Grammar,
    StringLeaf,
)

#TODO: Blocks (having its own return) vs. expressions
def _normalize_linecol(tokens: List[TokenInfo]) -> List[TokenInfo]:
    if not tokens:
        return []
    # first token has line 1
    first_line = tokens[0].start[0]
    line_subtract = tokens[0].start[0] - 1  # Start with line 1
    column_subtract = tokens[0].start[1]  # Start with column 0
    def replace(t: TokenInfo) -> TokenInfo:
        if t.start[0] == first_line:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1] - column_subtract),
                              end=(t.end[0] - line_subtract, t.end[1] - column_subtract))
        else:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1]),
                              end=(t.end[0] - line_subtract, t.end[1]))
    return list(map(replace, tokens))


class Base(DefaultParser):
    @memoize
    def action_contents(self) -> Optional[str]:
        """Note: The result should be parsable by ast.parse."""
        m = self.mark()
        level = 1
        has_return_stmt = False
        tokens = []
        prevmark = m
        while True:
            t = self._tokenizer.peek()
            if t.type == token.ENDMARKER:
                self.reset(m)
                return None
            self._tokenizer.getnext()
            if t.string == "}":
                level -= 1
                if level == 0:
                    break
            tokens.append(t)
            if t.string == "{":
                level += 1
            elif t.string == "return":
                has_return_stmt = True
            prevmark = self.mark()
        self.reset(prevmark) # Don't consume the last right brace
        tokens = _normalize_linecol(tokens)
        s = tokenize.untokenize(tokens)
        if self._verbose:
            print("##", repr(s))
        return s

# Keywords and soft keywords are listed at the end of the parser definition.
class GeneratedParser(Base):

    @memoize
    def start(self) -> RuleResult[Grammar]:
        # start: grammar $
        mark = self.mark()
        if (
            ((_temp := (self.grammar())).ok, grammar := _temp.value)[0]
            and
            (self.endmarker()).ok
        ):
            return [_temp, grammar]
        self.reset(mark)
        return failure[Grammar]()

    @memoize
    def grammar(self) -> RuleResult[Grammar]:
        # grammar: metas? rules extern_rules?
        mark = self.mark()
        if (
            ((_temp_1 := (success(_temp.value) if (_temp := (self.metas())).ok else success(RuleResultValue.FAIL_OK))).ok, metas := _temp_1.value)[0]
            and
            ((_temp_2 := (self.rules())).ok, rules := _temp_2.value)[0]
            and
            ((_temp_4 := (success(_temp_3.value) if (_temp_3 := (self.extern_rules())).ok else success(RuleResultValue.FAIL_OK))).ok, extern_rules := _temp_4.value)[0]
        ):
            return Grammar(rules, extern_rules or [], metas or [])
        self.reset(mark)
        return failure[Grammar]()

    @memoize
    def metas(self) -> RuleResult[List [MetaTuple]]:
        # metas: meta metas | meta
        mark = self.mark()
        if (
            ((_temp := (self.meta())).ok, meta := _temp.value)[0]
            and
            ((_temp_1 := (self.metas())).ok, metas := _temp_1.value)[0]
        ):
            return [meta] + metas
        self.reset(mark)
        if (
            ((_temp := (self.meta())).ok, meta := _temp.value)[0]
        ):
            return [meta]
        self.reset(mark)
        return failure[List [MetaTuple]]()

    @memoize
    def meta(self) -> RuleResult[MetaTuple]:
        # meta: "@" NAME NEWLINE | "@" NAME NAME NEWLINE | "@" NAME STRING NEWLINE
        mark = self.mark()
        if (
            (self.match_string("@")).ok
            and
            ((_temp := (self.name())).ok, name := _temp.value)[0]
            and
            (self.newline()).ok
        ):
            return (name.string, None)
        self.reset(mark)
        if (
            (self.match_string("@")).ok
            and
            ((_temp := (self.name())).ok, a := _temp.value)[0]
            and
            ((_temp_1 := (self.name())).ok, b := _temp_1.value)[0]
            and
            (self.newline()).ok
        ):
            return (a.string, b.string)
        self.reset(mark)
        if (
            (self.match_string("@")).ok
            and
            ((_temp := (self.name())).ok, name := _temp.value)[0]
            and
            ((_temp_1 := (self.string())).ok, string := _temp_1.value)[0]
            and
            (self.newline()).ok
        ):
            return (name.string, literal_eval(string.string))
        self.reset(mark)
        return failure[MetaTuple]()

    @memoize
    def rules(self) -> RuleResult[List [Rule]]:
        # rules: rule rules | rule
        mark = self.mark()
        if (
            ((_temp := (self.rule())).ok, rule := _temp.value)[0]
            and
            ((_temp_1 := (self.rules())).ok, rules := _temp_1.value)[0]
        ):
            return [rule] + rules
        self.reset(mark)
        if (
            ((_temp := (self.rule())).ok, rule := _temp.value)[0]
        ):
            return [rule]
        self.reset(mark)
        return failure[List [Rule]]()

    @memoize
    def rule(self) -> RuleResult[Rule]:
        # rule: rulename memoflag? ":" rule_rhs
        mark = self.mark()
        if (
            ((_temp := (self.rulename())).ok, rulename := _temp.value)[0]
            and
            ((_temp_2 := (success(_temp_1.value) if (_temp_1 := (self.memoflag())).ok else success(RuleResultValue.FAIL_OK))).ok, opt := _temp_2.value)[0]
            and
            (self.match_string(":")).ok
            and
            ((_temp_3 := (self.rule_rhs())).ok, rule_rhs := _temp_3.value)[0]
        ):
            return Rule(rulename[0], rulename[1], rule_rhs, memo=opt)
        self.reset(mark)
        return failure[Rule]()

    @memoize
    def extern_rules(self) -> RuleResult[List [ExternDecl]]:
        # extern_rules: extern_rule extern_rules | extern_rule
        mark = self.mark()
        if (
            ((_temp := (self.extern_rule())).ok, extern_rule := _temp.value)[0]
            and
            ((_temp_1 := (self.extern_rules())).ok, extern_rules := _temp_1.value)[0]
        ):
            return [extern_rule] + extern_rules
        self.reset(mark)
        if (
            ((_temp := (self.extern_rule())).ok, extern_rule := _temp.value)[0]
        ):
            return [extern_rule]
        self.reset(mark)
        return failure[List [ExternDecl]]()

    @memoize
    def extern_rule(self) -> RuleResult[ExternDecl]:
        # extern_rule: "extern" NAME annotation? NEWLINE
        mark = self.mark()
        if (
            (self.match_string("extern")).ok
            and
            ((_temp := (self.name())).ok, name := _temp.value)[0]
            and
            ((_temp_2 := (success(_temp_1.value) if (_temp_1 := (self.annotation())).ok else success(RuleResultValue.FAIL_OK))).ok, ann := _temp_2.value)[0]
            and
            (self.newline()).ok
        ):
            return ExternDecl(name.string, ann)
        self.reset(mark)
        return failure[ExternDecl]()

    @memoize
    def rulename(self) -> RuleResult[RuleName]:
        # rulename: NAME annotation | NAME
        mark = self.mark()
        if (
            ((_temp := (self.name())).ok, name := _temp.value)[0]
            and
            ((_temp_1 := (self.annotation())).ok, annotation := _temp_1.value)[0]
        ):
            return (name.string, annotation)
        self.reset(mark)
        if (
            ((_temp := (self.name())).ok, name := _temp.value)[0]
        ):
            return (name.string, None)
        self.reset(mark)
        return failure[RuleName]()

    @memoize
    def rule_rhs(self) -> RuleResult[Rhs]:
        # rule_rhs: alts? NEWLINE INDENT more_alts DEDENT | NEWLINE INDENT alt NEWLINE DEDENT | alts NEWLINE
        mark = self.mark()
        if (
            ((_temp_1 := (success(_temp.value) if (_temp := (self.alts())).ok else success(RuleResultValue.FAIL_OK))).ok, alts := _temp_1.value)[0]
            and
            (self.newline()).ok
            and
            (self.indent()).ok
            and
            ((_temp_2 := (self.more_alts())).ok, more_alts := _temp_2.value)[0]
            and
            (self.dedent()).ok
        ):
            return Rhs(alts.alts + more_alts.alts) if alts else more_alts
        self.reset(mark)
        if (
            (self.newline()).ok
            and
            (self.indent()).ok
            and
            ((_temp := (self.alt())).ok, alt := _temp.value)[0]
            and
            (self.newline()).ok
            and
            (self.dedent()).ok
        ):
            return Rhs([alt])
        self.reset(mark)
        if (
            ((_temp := (self.alts())).ok, alts := _temp.value)[0]
            and
            (self.newline()).ok
        ):
            return alts
        self.reset(mark)
        return failure[Rhs]()

    @memoize
    def memoflag(self) -> RuleResult[str]:
        # memoflag: '(' "memo" ')'
        mark = self.mark()
        if (
            (self.match_string('(')).ok
            and
            (self.match_string("memo")).ok
            and
            (self.match_string(')')).ok
        ):
            return "memo"
        self.reset(mark)
        return failure[str]()

    @memoize
    def alts(self) -> RuleResult[Rhs]:
        # alts: alt "|" alts | alt
        mark = self.mark()
        if (
            ((_temp := (self.alt())).ok, alt := _temp.value)[0]
            and
            (self.match_string("|")).ok
            and
            ((_temp_1 := (self.alts())).ok, alts := _temp_1.value)[0]
        ):
            return Rhs([alt] + alts.alts)
        self.reset(mark)
        if (
            ((_temp := (self.alt())).ok, alt := _temp.value)[0]
        ):
            return Rhs([alt])
        self.reset(mark)
        return failure[Rhs]()

    @memoize
    def more_alts(self) -> RuleResult[Rhs]:
        # more_alts: "|" alts NEWLINE more_alts | "|" alts NEWLINE
        mark = self.mark()
        if (
            (self.match_string("|")).ok
            and
            ((_temp := (self.alts())).ok, alts := _temp.value)[0]
            and
            (self.newline()).ok
            and
            ((_temp_1 := (self.more_alts())).ok, more_alts := _temp_1.value)[0]
        ):
            return Rhs(alts.alts + more_alts.alts)
        self.reset(mark)
        if (
            (self.match_string("|")).ok
            and
            ((_temp := (self.alts())).ok, alts := _temp.value)[0]
            and
            (self.newline()).ok
        ):
            return Rhs(alts.alts)
        self.reset(mark)
        return failure[Rhs]()

    @memoize
    def alt(self) -> RuleResult[Alt]:
        # alt: items '$' action | items '$' | items action | items | '$'
        mark = self.mark()
        if (
            ((_temp := (self.items())).ok, items := _temp.value)[0]
            and
            (self.match_string('$')).ok
            and
            ((_temp_1 := (self.action())).ok, action := _temp_1.value)[0]
        ):
            return Alt(items + [TopLevelItem(None, NameLeaf('ENDMARKER'))], action=action)
        self.reset(mark)
        if (
            ((_temp := (self.items())).ok, items := _temp.value)[0]
            and
            (self.match_string('$')).ok
        ):
            return Alt(items + [TopLevelItem(None, NameLeaf('ENDMARKER'))], action=None)
        self.reset(mark)
        if (
            ((_temp := (self.items())).ok, items := _temp.value)[0]
            and
            ((_temp_1 := (self.action())).ok, action := _temp_1.value)[0]
        ):
            return Alt(items, action=action)
        self.reset(mark)
        if (
            ((_temp := (self.items())).ok, items := _temp.value)[0]
        ):
            return Alt(items, action=None)
        self.reset(mark)
        if (
            (self.match_string('$')).ok
        ):
            return Alt([], action=None)
        self.reset(mark)
        return failure[Alt]()

    @memoize
    def items(self) -> RuleResult[List [TopLevelItem]]:
        # items: top_level_item items | top_level_item
        mark = self.mark()
        if (
            ((_temp := (self.top_level_item())).ok, top_level_item := _temp.value)[0]
            and
            ((_temp_1 := (self.items())).ok, items := _temp_1.value)[0]
        ):
            return [top_level_item] + items
        self.reset(mark)
        if (
            ((_temp := (self.top_level_item())).ok, top_level_item := _temp.value)[0]
        ):
            return [top_level_item]
        self.reset(mark)
        return failure[List [TopLevelItem]]()

    @memoize
    def top_level_item(self) -> RuleResult[TopLevelItem]:
        # top_level_item: NAME annotation '=' ~ item | NAME '=' ~ item | item | top_level_others
        mark = self.mark()
        cut = False
        if (
            ((_temp := (self.name())).ok, name := _temp.value)[0]
            and
            ((_temp_1 := (self.annotation())).ok, annotation := _temp_1.value)[0]
            and
            (self.match_string('=')).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp_2 := (self.item())).ok, item := _temp_2.value)[0]
        ):
            return TopLevelItem(name.string, item, annotation)
        self.reset(mark)
        if cut:
            return None
        cut = False
        if (
            ((_temp := (self.name())).ok, name := _temp.value)[0]
            and
            (self.match_string('=')).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp_1 := (self.item())).ok, item := _temp_1.value)[0]
        ):
            return TopLevelItem(name.string, item)
        self.reset(mark)
        if cut:
            return None
        if (
            ((_temp := (self.item())).ok, item := _temp.value)[0]
        ):
            return TopLevelItem(None, item)
        self.reset(mark)
        if (
            ((_temp := (self.top_level_others())).ok, it := _temp.value)[0]
        ):
            return TopLevelItem(None, it)
        self.reset(mark)
        return failure[TopLevelItem]()

    @memoize
    def top_level_others(self) -> RuleResult[LookaheadOrCut]:
        # top_level_others: '&' '&' ~ atom | '&' ~ atom | '!' ~ atom | '~'
        mark = self.mark()
        cut = False
        if (
            (self.match_string('&')).ok
            and
            (self.match_string('&')).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp := (self.atom())).ok, atom := _temp.value)[0]
        ):
            return Forced(atom)
        self.reset(mark)
        if cut:
            return None
        cut = False
        if (
            (self.match_string('&')).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp := (self.atom())).ok, atom := _temp.value)[0]
        ):
            return PositiveLookahead(atom)
        self.reset(mark)
        if cut:
            return None
        cut = False
        if (
            (self.match_string('!')).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp := (self.atom())).ok, atom := _temp.value)[0]
        ):
            return NegativeLookahead(atom)
        self.reset(mark)
        if cut:
            return None
        if (
            (self.match_string('~')).ok
        ):
            return Cut()
        self.reset(mark)
        return failure[LookaheadOrCut]()

    @memoize
    def item(self) -> RuleResult[Item]:
        # item: '[' ~ alts ']' | atom '?' | atom '*' | atom '+' | atom '.' atom '+' | atom
        mark = self.mark()
        cut = False
        if (
            (self.match_string('[')).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp := (self.alts())).ok, alts := _temp.value)[0]
            and
            (self.match_string(']')).ok
        ):
            return Opt(Group(alts))
        self.reset(mark)
        if cut:
            return None
        if (
            ((_temp := (self.atom())).ok, atom := _temp.value)[0]
            and
            (self.match_string('?')).ok
        ):
            return Opt(atom)
        self.reset(mark)
        if (
            ((_temp := (self.atom())).ok, atom := _temp.value)[0]
            and
            (self.match_string('*')).ok
        ):
            return Repeat0(atom)
        self.reset(mark)
        if (
            ((_temp := (self.atom())).ok, atom := _temp.value)[0]
            and
            (self.match_string('+')).ok
        ):
            return Repeat1(atom)
        self.reset(mark)
        if (
            ((_temp := (self.atom())).ok, sep := _temp.value)[0]
            and
            (self.match_string('.')).ok
            and
            ((_temp_1 := (self.atom())).ok, node := _temp_1.value)[0]
            and
            (self.match_string('+')).ok
        ):
            return Gather(sep, node)
        self.reset(mark)
        if (
            ((_temp := (self.atom())).ok, atom := _temp.value)[0]
        ):
            return atom
        self.reset(mark)
        return failure[Item]()

    @memoize
    def atom(self) -> RuleResult[Plain]:
        # atom: '(' ~ alts ')' | NAME | STRING
        mark = self.mark()
        cut = False
        if (
            (self.match_string('(')).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp := (self.alts())).ok, alts := _temp.value)[0]
            and
            (self.match_string(')')).ok
        ):
            return Group(alts)
        self.reset(mark)
        if cut:
            return None
        if (
            ((_temp := (self.name())).ok, name := _temp.value)[0]
        ):
            return NameLeaf(name.string)
        self.reset(mark)
        if (
            ((_temp := (self.string())).ok, string := _temp.value)[0]
        ):
            return StringLeaf(string.string)
        self.reset(mark)
        return failure[Plain]()

    @memoize
    def action(self) -> RuleResult[str]:
        # action: "{" ~ action_contents "}"
        mark = self.mark()
        cut = False
        if (
            (self.match_string("{")).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp := (self.action_contents())).ok, action_contents := _temp.value)[0]
            and
            (self.match_string("}")).ok
        ):
            return action_contents
        self.reset(mark)
        if cut:
            return None
        return failure[str]()

    @memoize
    def annotation(self) -> RuleResult[str]:
        # annotation: "[" ~ target_atoms "]"
        mark = self.mark()
        cut = False
        if (
            (self.match_string("[")).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp := (self.target_atoms())).ok, target_atoms := _temp.value)[0]
            and
            (self.match_string("]")).ok
        ):
            return target_atoms
        self.reset(mark)
        if cut:
            return None
        return failure[str]()

    @memoize
    def target_atoms(self) -> RuleResult[str]:
        # target_atoms: target_atom target_atoms | target_atom
        mark = self.mark()
        if (
            ((_temp := (self.target_atom())).ok, target_atom := _temp.value)[0]
            and
            ((_temp_1 := (self.target_atoms())).ok, target_atoms := _temp_1.value)[0]
        ):
            return target_atom + " " + target_atoms
        self.reset(mark)
        if (
            ((_temp := (self.target_atom())).ok, target_atom := _temp.value)[0]
        ):
            return target_atom
        self.reset(mark)
        return failure[str]()

    @memoize
    def target_atom(self) -> RuleResult[str]:
        # target_atom: "{" ~ target_atoms? "}" | "[" ~ target_atoms? "]" | NAME "*" | NAME | NUMBER | STRING | FSTRING_START target_fstring_middle* FSTRING_END | "?" | ":" | !"}" !"]" OP
        mark = self.mark()
        cut = False
        if (
            (self.match_string("{")).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp_1 := (success(_temp.value) if (_temp := (self.target_atoms())).ok else success(RuleResultValue.FAIL_OK))).ok, atoms := _temp_1.value)[0]
            and
            (self.match_string("}")).ok
        ):
            return "{" + (atoms or "") + "}"
        self.reset(mark)
        if cut:
            return None
        cut = False
        if (
            (self.match_string("[")).ok
            and
            (cut := (success[bool]()).ok)
            and
            ((_temp_1 := (success(_temp.value) if (_temp := (self.target_atoms())).ok else success(RuleResultValue.FAIL_OK))).ok, atoms := _temp_1.value)[0]
            and
            (self.match_string("]")).ok
        ):
            return "[" + (atoms or "") + "]"
        self.reset(mark)
        if cut:
            return None
        if (
            ((_temp := (self.name())).ok, name := _temp.value)[0]
            and
            (self.match_string("*")).ok
        ):
            return name.string + "*"
        self.reset(mark)
        if (
            ((_temp := (self.name())).ok, name := _temp.value)[0]
        ):
            return name.string
        self.reset(mark)
        if (
            ((_temp := (self.number())).ok, number := _temp.value)[0]
        ):
            return number.string
        self.reset(mark)
        if (
            ((_temp := (self.string())).ok, string := _temp.value)[0]
        ):
            return string.string
        self.reset(mark)
        if (
            ((_temp := (self.fstring_start())).ok, l := _temp.value)[0]
            and
            ((_temp_1 := (self._loop0_1())).ok, m := _temp_1.value)[0]
            and
            ((_temp_2 := (self.fstring_end())).ok, r := _temp_2.value)[0]
        ):
            return l.string + "".join(m) + r.string
        self.reset(mark)
        if (
            (self.match_string("?")).ok
        ):
            return "?"
        self.reset(mark)
        if (
            (self.match_string(":")).ok
        ):
            return ":"
        self.reset(mark)
        if (
            (self.negative_lookahead(self.match_string, "}")).ok
            and
            (self.negative_lookahead(self.match_string, "]")).ok
            and
            ((_temp := (self.op())).ok, op := _temp.value)[0]
        ):
            return op.string
        self.reset(mark)
        return failure[str]()

    @memoize
    def target_fstring_middle(self) -> RuleResult[str]:
        # target_fstring_middle: FSTRING_MIDDLE | "{" | "}" | target_atom
        mark = self.mark()
        if (
            ((_temp := (self.fstring_middle())).ok, fstring_middle := _temp.value)[0]
        ):
            return fstring_middle.string
        self.reset(mark)
        if (
            (self.match_string("{")).ok
        ):
            return "{"
        self.reset(mark)
        if (
            (self.match_string("}")).ok
        ):
            return "}"
        self.reset(mark)
        if (
            ((_temp := (self.target_atom())).ok, target_atom := _temp.value)[0]
        ):
            return target_atom
        self.reset(mark)
        return failure[str]()

    @memoize
    def _loop0_1(self) -> RuleResult[Any]:
        # _loop0_1: target_fstring_middle
        mark = self.mark()
        children = []
        while (
            ((_temp := (self.target_fstring_middle())).ok, target_fstring_middle := _temp.value)[0]
        ):
            children.append([_temp, target_fstring_middle])
            mark = self.mark()
        self.reset(mark)
        return success[Any](children)

    KEYWORDS = ()
    SOFT_KEYWORDS = ('extern', 'memo')


if __name__ == '__main__':
    from pegen.parser_v2 import simple_parser_main
    simple_parser_main(GeneratedParser)
