#!/usr/bin/env python
# @generated by stde.pegen from src/stde/pegen/v2/metagrammar.gram

from typing import Any, Optional, Union
from stde.pegen.v2.parser import (
    memoize, memoize_left_rec, logger, DefaultParser, CharBasedParser,
    RuleResult, ResultFlag, ParseError, ParseFailure, NO_MATCH, FAILURE)
#from stde.pegen.v2.parser_old import memoize, memoize_left_rec, logger, DefaultParser, CharBasedParser #type:ignore
from ast import literal_eval
from typing import List, Union, Iterable
import token
import tokenize
from tokenize import TokenInfo

FAILURE = ResultFlag.FAILURE

from stde.pegen.v2.grammar import (
    Alt,
    Action,
    GrammarItem,
    Cut,
    ExternDecl,
    Forced,
    Gather,
    Group,
    Item,
    Lookahead,
    LookaheadOrCut,
    MetaTuple,
    NameLeaf,
    TopLevelItem,
    NegativeLookahead,
    Opt,
    Plain,
    PositiveLookahead,
    Repeat0,
    Repeat1,
    Rhs,
    Rule,
    RuleName,
    Grammar,
    StringLeaf,
)

#TODO: Blocks (having its own return) vs. expressions
def _normalize_linecol(tokens: List[TokenInfo]) -> List[TokenInfo]:
    if not tokens:
        return []
    # first token has line 1
    first_line = tokens[0].start[0]
    line_subtract = tokens[0].start[0] - 1  # Start with line 1
    column_subtract = tokens[0].start[1]  # Start with column 0
    def replace(t: TokenInfo) -> TokenInfo:
        if t.start[0] == first_line:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1] - column_subtract),
                              end=(t.end[0] - line_subtract, t.end[1] - column_subtract))
        else:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1]),
                              end=(t.end[0] - line_subtract, t.end[1]))
    return list(map(replace, tokens))


class Base(DefaultParser):
    @memoize #XXX:?
    def action_contents(self) -> RuleResult[Action]:
        """Note: The result should be parsable by ast.parse."""
        m = self.mark()
        level = 1
        is_stmts = False
        tokens = []
        prevmark = m
        while True:
            t = self._tokenizer.peek()
            if t.type == token.ENDMARKER:
                self.reset(m)
                return FAILURE
            self._tokenizer.getnext()
            if t.string == "}":
                level -= 1
                if level == 0:
                    break
            tokens.append(t)
            if t.string == "{":
                level += 1
            elif t.string == "return":
                is_stmts = True
            prevmark = self.mark()
        self.reset(prevmark) # Don't consume the last right brace
        tokens = _normalize_linecol(tokens)
        s = tokenize.untokenize(tokens)
        if self._verbose: #XXX: ...
            print("  " * self._level + "## Parsed code:", repr(s))
        return Action(s, is_stmts)

    # Temporary trick (plan to make it built-in)
    @logger
    def empty(self) -> RuleResult[None]:
        return None


# Keywords and soft keywords are listed at the end of the parser definition.
class GeneratedParser(Base):

    @memoize
    def r_start(self) -> RuleResult[Grammar]:
        # start: grammar $
        mark = self.mark()
        if (
            (grammar := (self.r_grammar())) is not FAILURE
            and
            (self.endmarker()) is not FAILURE
        ):
            return grammar
        self.reset(mark)
        return FAILURE

    @memoize
    def r_grammar(self) -> RuleResult[Grammar]:
        # grammar: meta* rule+ extern_decl*
        mark = self.mark()
        if (
            (metas := (self._loop0_1())) is not FAILURE
            and
            (rules := (self._loop1_2())) is not FAILURE
            and
            (extern_decls := (self._loop0_3())) is not FAILURE
        ):
            return Grammar(rules, extern_decls, metas)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_meta(self) -> RuleResult[MetaTuple]:
        # meta: "@" NAME NEWLINE | "@" NAME NAME NEWLINE | "@" NAME STRING NEWLINE
        mark = self.mark()
        if (
            (self.match_string("@")) is not FAILURE
            and
            (name := (self.name())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return (name.string, None)
        self.reset(mark)
        if (
            (self.match_string("@")) is not FAILURE
            and
            (a := (self.name())) is not FAILURE
            and
            (b := (self.name())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return (a.string, b.string)
        self.reset(mark)
        if (
            (self.match_string("@")) is not FAILURE
            and
            (name := (self.name())) is not FAILURE
            and
            (string := (self.string())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return (name.string, literal_eval(string.string))
        self.reset(mark)
        return FAILURE

    @memoize
    def r_rule(self) -> RuleResult[Rule]:
        # rule: rulename memoflag? ":" rule_rhs
        mark = self.mark()
        if (
            (rulename := (self.r_rulename())) is not FAILURE
            and
            (opt := (_temp if (_temp := (self.r_memoflag())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string(":")) is not FAILURE
            and
            (rule_rhs := (self.r_rule_rhs())) is not FAILURE
        ):
            return Rule(rulename[0], rulename[1], rule_rhs, memo=opt)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_extern_decl(self) -> RuleResult[ExternDecl]:
        # extern_decl: "extern" NAME annotation? NEWLINE
        mark = self.mark()
        if (
            (self.match_string("extern")) is not FAILURE
            and
            (name := (self.name())) is not FAILURE
            and
            (ann := (_temp if (_temp := (self.r_annotation())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return ExternDecl(name.string, ann or None)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_rulename(self) -> RuleResult[RuleName]:
        # rulename: NAME annotation?
        mark = self.mark()
        if (
            (name := (self.name())) is not FAILURE
            and
            (ann := (_temp if (_temp := (self.r_annotation())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return (name.string, ann or None)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_rule_rhs(self) -> RuleResult[Rhs]:
        # rule_rhs: NEWLINE INDENT alts NEWLINE DEDENT | alts? NEWLINE [(INDENT more_alts DEDENT)] | action NEWLINE | NEWLINE INDENT action NEWLINE DEDENT
        mark = self.mark()
        if (
            (self.newline()) is not FAILURE
            and
            (self.indent()) is not FAILURE
            and
            (alts := (self.r_alts())) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (self.dedent()) is not FAILURE
        ):
            return alts
        self.reset(mark)
        if (
            (alts := (_temp if (_temp := (self.r_alts())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (m := (_temp_1 if (_temp_1 := (self._tmp_4())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return Rhs((alts.alts if alts else []) + (m[1].alts if m else []))
        self.reset(mark)
        if (
            (action := (self.r_action())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return Rhs([Alt([], action=action)])
        self.reset(mark)
        if (
            (self.newline()) is not FAILURE
            and
            (self.indent()) is not FAILURE
            and
            (action := (self.r_action())) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (self.dedent()) is not FAILURE
        ):
            return Rhs([Alt([], action=action)])
        self.reset(mark)
        return FAILURE

    @memoize
    def r_a(self) -> RuleResult[Any]:
        # a: 
        # nullable
        mark = self.mark()
        if True: # Empty branch
            return 1
        self.reset(mark)
        return FAILURE

    @memoize
    def r_memoflag(self) -> RuleResult[str]:
        # memoflag: '(' "memo" ')'
        mark = self.mark()
        if (
            (self.match_string('(')) is not FAILURE
            and
            (self.match_string("memo")) is not FAILURE
            and
            (self.match_string(')')) is not FAILURE
        ):
            return "memo"
        self.reset(mark)
        return FAILURE

    @memoize
    def r_alts(self) -> RuleResult[Rhs]:
        # alts: "|".alt+
        mark = self.mark()
        if (
            (alts := (self._gather_6())) is not FAILURE
        ):
            return Rhs(alts)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_more_alts(self) -> RuleResult[Rhs]:
        # more_alts: (("|" alt NEWLINE?))+
        mark = self.mark()
        if (
            (alts := (self._loop1_7())) is not FAILURE
        ):
            return Rhs(list(map(lambda x: x[1], alts)))
        self.reset(mark)
        return FAILURE

    @memoize
    def r_alt(self) -> RuleResult[Alt]:
        # alt: top_level_item+ '$'? action? | '$' action?
        mark = self.mark()
        if (
            (items := (self._loop1_8())) is not FAILURE
            and
            (e := (_temp if (_temp := (self.match_string('$'))) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (action := (_temp_1 if (_temp_1 := (self.r_action())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return Alt(items + [TopLevelItem(None, NameLeaf('ENDMARKER'))] if e else items, action=action or None)
        self.reset(mark)
        if (
            (self.match_string('$')) is not FAILURE
            and
            (action := (_temp if (_temp := (self.r_action())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return Alt([TopLevelItem(None, NameLeaf('ENDMARKER'))], action=action or None)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_top_level_item(self) -> RuleResult[TopLevelItem]:
        # top_level_item: NAME annotation '=' ~ item | NAME '=' ~ item | item | top_level_others
        mark = self.mark()
        __cut = False
        if (
            (name := (self.name())) is not FAILURE
            and
            (annotation := (self.r_annotation())) is not FAILURE
            and
            (self.match_string('=')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (item := (self.r_item())) is not FAILURE
        ):
            return TopLevelItem(name.string, item, annotation)
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (name := (self.name())) is not FAILURE
            and
            (self.match_string('=')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (item := (self.r_item())) is not FAILURE
        ):
            return TopLevelItem(name.string, item)
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (item := (self.r_item())) is not FAILURE
        ):
            return TopLevelItem(None, item)
        self.reset(mark)
        if (
            (it := (self.r_top_level_others())) is not FAILURE
        ):
            return TopLevelItem(None, it)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_top_level_others(self) -> RuleResult[LookaheadOrCut]:
        # top_level_others: '&' '&' ~ atom | '&' ~ atom | '!' ~ atom | '~'
        mark = self.mark()
        __cut = False
        if (
            (self.match_string('&')) is not FAILURE
            and
            (self.match_string('&')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atom := (self.r_atom())) is not FAILURE
        ):
            return Forced(atom)
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (self.match_string('&')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atom := (self.r_atom())) is not FAILURE
        ):
            return PositiveLookahead(atom)
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (self.match_string('!')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atom := (self.r_atom())) is not FAILURE
        ):
            return NegativeLookahead(atom)
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (self.match_string('~')) is not FAILURE
        ):
            return Cut()
        self.reset(mark)
        return FAILURE

    @memoize
    def r_item(self) -> RuleResult[Item]:
        # item: '[' ~ alts ']' | atom '?' | atom '*' | atom '+' | atom '.' atom '+' | atom
        mark = self.mark()
        __cut = False
        if (
            (self.match_string('[')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (alts := (self.r_alts())) is not FAILURE
            and
            (self.match_string(']')) is not FAILURE
        ):
            return Opt(Group(alts))
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (atom := (self.r_atom())) is not FAILURE
            and
            (self.match_string('?')) is not FAILURE
        ):
            return Opt(atom)
        self.reset(mark)
        if (
            (atom := (self.r_atom())) is not FAILURE
            and
            (self.match_string('*')) is not FAILURE
        ):
            return Repeat0(atom)
        self.reset(mark)
        if (
            (atom := (self.r_atom())) is not FAILURE
            and
            (self.match_string('+')) is not FAILURE
        ):
            return Repeat1(atom)
        self.reset(mark)
        if (
            (sep := (self.r_atom())) is not FAILURE
            and
            (self.match_string('.')) is not FAILURE
            and
            (node := (self.r_atom())) is not FAILURE
            and
            (self.match_string('+')) is not FAILURE
        ):
            return Gather(sep, node)
        self.reset(mark)
        if (
            (atom := (self.r_atom())) is not FAILURE
        ):
            return atom
        self.reset(mark)
        return FAILURE

    @memoize
    def r_atom(self) -> RuleResult[Plain]:
        # atom: '(' ~ alts ')' | NAME | STRING
        mark = self.mark()
        __cut = False
        if (
            (self.match_string('(')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (alts := (self.r_alts())) is not FAILURE
            and
            (self.match_string(')')) is not FAILURE
        ):
            return Group(alts)
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (name := (self.name())) is not FAILURE
        ):
            return NameLeaf(name.string)
        self.reset(mark)
        if (
            (string := (self.string())) is not FAILURE
        ):
            return StringLeaf(string.string)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_action(self) -> RuleResult[Action]:
        # action: "{" ~ action_contents "}"
        mark = self.mark()
        __cut = False
        if (
            (self.match_string("{")) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (action_contents := (self.action_contents())) is not FAILURE
            and
            (self.match_string("}")) is not FAILURE
        ):
            return action_contents
        self.reset(mark)
        if __cut:
            return FAILURE
        return FAILURE

    @memoize
    def r_annotation(self) -> RuleResult[str]:
        # annotation: "[" ~ target_atoms "]"
        mark = self.mark()
        __cut = False
        if (
            (self.match_string("[")) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (target_atoms := (self.r_target_atoms())) is not FAILURE
            and
            (self.match_string("]")) is not FAILURE
        ):
            return target_atoms
        self.reset(mark)
        if __cut:
            return FAILURE
        return FAILURE

    @memoize
    def r_target_atoms(self) -> RuleResult[str]:
        # target_atoms: target_atom target_atoms | target_atom
        mark = self.mark()
        if (
            (target_atom := (self.r_target_atom())) is not FAILURE
            and
            (target_atoms := (self.r_target_atoms())) is not FAILURE
        ):
            return target_atom + " " + target_atoms
        self.reset(mark)
        if (
            (target_atom := (self.r_target_atom())) is not FAILURE
        ):
            return target_atom
        self.reset(mark)
        return FAILURE

    @memoize
    def r_target_atom(self) -> RuleResult[str]:
        # target_atom: "{" ~ target_atoms? "}" | "[" ~ target_atoms? "]" | NAME "*" | NAME | NUMBER | STRING | FSTRING_START target_fstring_middle* FSTRING_END | "?" | ":" | !"}" !"]" OP
        mark = self.mark()
        __cut = False
        if (
            (self.match_string("{")) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atoms := (_temp if (_temp := (self.r_target_atoms())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string("}")) is not FAILURE
        ):
            return "{" + (atoms or "") + "}"
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (self.match_string("[")) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atoms := (_temp if (_temp := (self.r_target_atoms())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string("]")) is not FAILURE
        ):
            return "[" + (atoms or "") + "]"
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (name := (self.name())) is not FAILURE
            and
            (self.match_string("*")) is not FAILURE
        ):
            return name.string + "*"
        self.reset(mark)
        if (
            (name := (self.name())) is not FAILURE
        ):
            return name.string
        self.reset(mark)
        if (
            (number := (self.number())) is not FAILURE
        ):
            return number.string
        self.reset(mark)
        if (
            (string := (self.string())) is not FAILURE
        ):
            return string.string
        self.reset(mark)
        if (
            (l := (self.fstring_start())) is not FAILURE
            and
            (m := (self._loop0_9())) is not FAILURE
            and
            (r := (self.fstring_end())) is not FAILURE
        ):
            return l.string + "".join(m) + r.string
        self.reset(mark)
        if (
            (self.match_string("?")) is not FAILURE
        ):
            return "?"
        self.reset(mark)
        if (
            (self.match_string(":")) is not FAILURE
        ):
            return ":"
        self.reset(mark)
        if (
            (self.negative_lookahead(self.match_string, "}")) is not FAILURE
            and
            (self.negative_lookahead(self.match_string, "]")) is not FAILURE
            and
            (op := (self.op())) is not FAILURE
        ):
            return op.string
        self.reset(mark)
        return FAILURE

    @memoize
    def r_target_fstring_middle(self) -> RuleResult[str]:
        # target_fstring_middle: FSTRING_MIDDLE | "{" | "}" | target_atom
        mark = self.mark()
        if (
            (fstring_middle := (self.fstring_middle())) is not FAILURE
        ):
            return fstring_middle.string
        self.reset(mark)
        if (
            (self.match_string("{")) is not FAILURE
        ):
            return "{"
        self.reset(mark)
        if (
            (self.match_string("}")) is not FAILURE
        ):
            return "}"
        self.reset(mark)
        if (
            (target_atom := (self.r_target_atom())) is not FAILURE
        ):
            return target_atom
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop0_1(self) -> RuleResult[Any]:
        # _loop0_1: meta
        mark = self.mark()
        children = []
        while (
            (meta := (self.r_meta())) is not FAILURE
        ):
            children.append(meta)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _loop1_2(self) -> RuleResult[Any]:
        # _loop1_2: rule
        mark = self.mark()
        children = []
        while (
            (rule := (self.r_rule())) is not FAILURE
        ):
            children.append(rule)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop0_3(self) -> RuleResult[Any]:
        # _loop0_3: extern_decl
        mark = self.mark()
        children = []
        while (
            (extern_decl := (self.r_extern_decl())) is not FAILURE
        ):
            children.append(extern_decl)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _tmp_4(self) -> RuleResult[Any]:
        # _tmp_4: INDENT more_alts DEDENT
        mark = self.mark()
        if (
            (indent := (self.indent())) is not FAILURE
            and
            (more_alts := (self.r_more_alts())) is not FAILURE
            and
            (dedent := (self.dedent())) is not FAILURE
        ):
            return [indent, more_alts, dedent]
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop0_5(self) -> RuleResult[Any]:
        # _loop0_5: "|" alt
        mark = self.mark()
        children = []
        while (
            (self.match_string("|")) is not FAILURE
            and
            (elem := (self.r_alt())) is not FAILURE
        ):
            children.append(elem)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _gather_6(self) -> RuleResult[Any]:
        # _gather_6: alt _loop0_5
        mark = self.mark()
        if (
            (elem := (self.r_alt())) is not FAILURE
            is not None
            and
            (seq := (self._loop0_5())) is not FAILURE
            is not None
        ):
            return [elem] + seq
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop1_7(self) -> RuleResult[Any]:
        # _loop1_7: ("|" alt NEWLINE?)
        mark = self.mark()
        children = []
        while (
            (_tmp_10 := (self._tmp_10())) is not FAILURE
        ):
            children.append(_tmp_10)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop1_8(self) -> RuleResult[Any]:
        # _loop1_8: top_level_item
        mark = self.mark()
        children = []
        while (
            (top_level_item := (self.r_top_level_item())) is not FAILURE
        ):
            children.append(top_level_item)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop0_9(self) -> RuleResult[Any]:
        # _loop0_9: target_fstring_middle
        mark = self.mark()
        children = []
        while (
            (target_fstring_middle := (self.r_target_fstring_middle())) is not FAILURE
        ):
            children.append(target_fstring_middle)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _tmp_10(self) -> RuleResult[Any]:
        # _tmp_10: "|" alt NEWLINE?
        mark = self.mark()
        if (
            (__literal := (self.match_string("|"))) is not FAILURE
            and
            (alt := (self.r_alt())) is not FAILURE
            and
            (opt := (_temp if (_temp := (self.newline())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return [__literal, alt, opt]
        self.reset(mark)
        return FAILURE

    def start(self) -> Union[Grammar, ParseFailure]:
        try:
            value = self.r_start()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def grammar(self) -> Union[Grammar, ParseFailure]:
        try:
            value = self.r_grammar()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def meta(self) -> Union[MetaTuple, ParseFailure]:
        try:
            value = self.r_meta()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def rule(self) -> Union[Rule, ParseFailure]:
        try:
            value = self.r_rule()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def extern_decl(self) -> Union[ExternDecl, ParseFailure]:
        try:
            value = self.r_extern_decl()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def rulename(self) -> Union[RuleName, ParseFailure]:
        try:
            value = self.r_rulename()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def rule_rhs(self) -> Union[Rhs, ParseFailure]:
        try:
            value = self.r_rule_rhs()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def a(self) -> Union[None, ParseFailure]:
        try:
            value = self.r_a()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def memoflag(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_memoflag()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def alts(self) -> Union[Rhs, ParseFailure]:
        try:
            value = self.r_alts()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def more_alts(self) -> Union[Rhs, ParseFailure]:
        try:
            value = self.r_more_alts()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def alt(self) -> Union[Alt, ParseFailure]:
        try:
            value = self.r_alt()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def top_level_item(self) -> Union[TopLevelItem, ParseFailure]:
        try:
            value = self.r_top_level_item()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def top_level_others(self) -> Union[LookaheadOrCut, ParseFailure]:
        try:
            value = self.r_top_level_others()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def item(self) -> Union[Item, ParseFailure]:
        try:
            value = self.r_item()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def atom(self) -> Union[Plain, ParseFailure]:
        try:
            value = self.r_atom()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def action(self) -> Union[Action, ParseFailure]:
        try:
            value = self.r_action()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def annotation(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_annotation()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def target_atoms(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_target_atoms()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def target_atom(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_target_atom()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    def target_fstring_middle(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_target_fstring_middle()
            return ParseFailure() if value is FAILURE else value
        except ParseError as e:
            return ParseFailure(parse_exc=e)

    KEYWORDS = ()
    SOFT_KEYWORDS = ('extern', 'memo')


if __name__ == '__main__':
    from stde.pegen.v2.parser import simple_parser_main
    simple_parser_main(GeneratedParser)
