#!/usr/bin/env python
# @generated by stde.pegen from src/stde/pegen/v2/metagrammar.gram

from typing import Any, Optional, Union
from stde.pegen.v2.parser import (
    memoize, memoize_left_rec, logger, DefaultParser, CharBasedParser,
    RuleResult, ResultFlag, ParseError, ParseFailure, NO_MATCH, FAILURE)
\
#from stde.pegen.v2.parser_old import memoize, memoize_left_rec, logger, DefaultParser, CharBasedParser #type:ignore
from ast import literal_eval
import ast
from typing import List, Union, Iterable, TextIO, Any, Self, Tuple
import token
import tokenize
import textwrap
from tokenize import TokenInfo
from stde.pegen.v2.parser import ParseError

FAILURE = ResultFlag.FAILURE

from stde.pegen.v2.grammar import (
    Alt,
    Action,
    GrammarItem,
    Cut,
    ExternDecl,
    Forced,
    Gather,
    Group,
    Item,
    Lookahead,
    LookaheadOrCut,
    MetaTuple,
    NameLeaf,
    TopLevelItem,
    NegativeLookahead,
    Opt,
    Plain,
    PositiveLookahead,
    Repeat0,
    Repeat1,
    Rhs,
    Rule,
    RuleName,
    Grammar,
    StringLeaf,
)

# XXX: Is there a way to get the mark of the previous token?

def _normalize_linecol(tokens: List[TokenInfo]) -> List[TokenInfo]:
    if not tokens:
        return []
    # first token has line 1
    first_line = tokens[0].start[0]
    line_subtract = tokens[0].start[0] - 1  # Start with line 1
    column_subtract = tokens[0].start[1]  # Start with column 0
    def replace(t: TokenInfo) -> TokenInfo:
        if t.start[0] == first_line:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1] - column_subtract),
                              end=(t.end[0] - line_subtract, t.end[1] - column_subtract))
        else:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1]),
                              end=(t.end[0] - line_subtract, t.end[1]))
    return list(map(replace, tokens))


def _slice_line_col2(text: str, start: Tuple[int, int], end: Tuple[int, int]) -> str:
    """Slice text from start to end ((line, column) tuples, 1-based line, 0-based column)."""
    return _slice_line_col(text, (start[0] - 1, start[1]), (end[0] - 1, end[1]))

def _slice_line_col(text: str, start: Tuple[int, int], end: Tuple[int, int]) -> str:
    """Slice text from start to end ((line, column) tuples, both 0-based)."""
    st, ed = _start_end_line_col_to_index(text, start, end)
    return text[st:ed]

def _start_end_line_col_to_index(text: str, start: Tuple[int, int], end: Tuple[int, int]) -> Tuple[int, int]:
    """Convert (line, col) (both 0-based) to indexes."""
    # XXX: I think the assumptions of the assertions here still hold
    # because it's only used from _slice_line_col2
    # and ultimately `start` and `end` are positions that exist in original text
    # so return None case won't happen
    assert (i := _forward_lines(text, 0, start[0], 0)) is not None
    st = i + 1 + start[1] # Not i + start[1], i is position of newline
    # Note: It's possible that a newline occurs at index `st`, so `left_limit` is `st`
    # By the way, replacing `st` with `i + 1` will also work, but I'm not doing that
    assert (i := _forward_lines(text, st, end[0] - start[0], i)) is not None
    return (st, i + 1 + end[1])

def _forward_lines(text: str, left_limit: int, n: int, zero_default: int) -> Optional[int]:
    """Returns the position of the `n`-th newline after `left_limit` in `text`.

    If `text[left_limit]` is `"\n"`, it's included in the count, in the sense that
    `_forward_lines(text, left_limit, 1, zero_default)` will be `left_limit`.

    If `n` is 0, returns `zero_default`.

    If there are less than `n` newlines after (including) `left_limit`, returns `None`.
    """
    if not n:
        return zero_default
    while n:
        i = text.find("\n", left_limit)
        if i == -1:
            return None
        n -= 1
        left_limit = i + 1
    return i

class Base(DefaultParser):
    """Note: Do not create an instance by calling __init__.
    Instead, use class methods from_stream and from_text.
    """
    # In action_contents it's difficult to dedent the text correctly without knowing the source,
    # so we modify the constructors to do that.
    #
    # It's theoretically possible to retrieve the source text by piecing together the token.line's.
    # But I'll just skip that effort.
    # Furthermore `tokenize` parses the whole PEG grammar
    # and the PEG grammar is not valid Python
    # so if we depend on token.line we're experiencing more said (in docs)
    # "undefined behavior" ... haha
    #
    # (And, we can't drop support for parsing grammar with a stream -- yes,
    # it's arguably esoteric but the python_parser used for testing depends on it)

    _text: str
    _grammar_file_name: Optional[str]
    completely_propogate_parse_error: bool

    @classmethod
    def from_stream(cls, stream: TextIO, *args: Any, grammar_file_name: Optional[str] = None, **kwargs: Any) -> Self:
        text = stream.read()
        stream.seek(0)
        instance = super().from_stream(stream, *args, **kwargs)
        instance._text = text
        instance._grammar_file_name = grammar_file_name
        instance.completely_propogate_parse_error = False
        return instance

    @classmethod
    def from_text(cls, text: str, *args: Any, grammar_file_name: Optional[str] = None, **kwargs: Any) -> Self:
        instance = super().from_text(text, *args, **kwargs)
        instance._text = text
        instance._grammar_file_name = grammar_file_name
        instance.completely_propogate_parse_error = False
        return instance

    @property
    def effective_file_name(self) -> str:
        return "<grammar file>" if self._grammar_file_name is None else self._grammar_file_name

    @memoize #XXX:?
    def action(self) -> RuleResult[Action]:
        """Note: The result should be parsable by ast.parse."""
        # XXX: Validate with ast.parse at grammar parse time?
        m = self.mark()
        if (starting_brace := self.match_string("{")) is FAILURE:
            # XXX: Can hard-fail here to skip backtracking?
            self.reset(m)
            return FAILURE
        level = 1
        is_stmts = False
        tokens = []
        while True:
            t = self._tokenizer.peek()
            if t.type == token.ENDMARKER:
                self.reset(m)
                return FAILURE
            self._tokenizer.getnext()
            if t.string == "}":
                level -= 1
                closing_brace = t
                if level == 0:
                    break
            tokens.append(t)
            if t.string == "{":
                level += 1
            elif t.string == "return":
                is_stmts = True
        if not tokens:
            # XXX: This self.reset is missed in previous versions. We need to
            # keep an eye on what breaks
            self.reset(m)
            return FAILURE # Don't accept empty actions
        if self._verbose: #XXX: ...
            import pickle
            print("  " * self._level + "## Unnormalized:", pickle.dumps(tokens))
        if is_stmts:
            # TODO: Harden tests once rewritten with exec_ns
            if tokens[0].line == starting_brace.line:
                #line, col, line_text = self.diagnose()
                e = ParseError(
                    "If the action is statements, it cannot start on the same line as the left brace.",
                    (
                        self.effective_file_name,
                        tokens[0].start[0],
                        tokens[0].start[1] + 1, # Oddly tokenize's colnos are 0-based
                        tokens[0].line,
                        tokens[0].end[0],
                        tokens[0].end[1] + 1
                    )
                )
                e.add_note("An action is statements if it contains the keyword 'return'.")
                self.completely_propogate_parse_error = True
                raise e

            start_pos = (tokens[0].start[0] - 1, 0)
            end_pos = (closing_brace.start[0] - 1, closing_brace.start[1])
            st, ed = _start_end_line_col_to_index(self._text, start_pos, end_pos)
            text = self._text[st:ed]

            # The first line must be unindented to be valid Python
            # Find first non-empty line (assert must exist) to analyze its indent
            i = 0 # Now relative to `text`
            # These numbers, after adding with `start_pos`, should be the position relative to whole file
            ln = 0
            # Note: Can probably rewrite loop with str.splitlines but don't have much motivation now
            # (Letting the loop stay like this has the benefit of lower memory usage
            # in the case that the action would fail with "Mixed space/tab indent on first line.")
            while True:
                j = _forward_lines(text, i, 1, 0)
                if j is None:
                    # Note: Besides when all lines are blank, `j is None` may also happen when
                    # there is just no newline in sliced text:
                    #
                    #    rule: {
                    #        return 1}
                    #
                    # sliced text: "return 1"
                    if i == 0:
                        assert not text[i:j].isspace()
                        # Using j as result var anyway
                        j = ed - st
                        break
                    else:
                        assert False, "no non-empty line found in statements-type action code??"
                if not text[i:j].isspace():
                    # First line is text[i:j]
                    break
                i = j + 1
                ln += 1
            first_line = text[i:j]

            # If it contains mixed tab/space indent, it's an error
            type = " " if first_line[i] == " " else "\t" if first_line[i] == "\t" else None
            stripped_first_line = first_line.lstrip(type)
            assert stripped_first_line
            if stripped_first_line[0] == ("\t" if type == " " else " "):
                e = ParseError(
                    "Mixed space/tab indent on first line.",
                    (
                        self.effective_file_name,
                        start_pos[0] + ln,
                        start_pos[1] + 1, # Our `start_pos`'s colno is 0-based too
                        first_line,
                        start_pos[0] + ln,
                        start_pos[1] + (len(first_line) - len(first_line.lstrip())) + 1
                    )
                )
                self.completely_propogate_parse_error = True
                raise e
            dedent_chars = len(first_line) - len(stripped_first_line)

            # I think now we can comfortably use splitlines, can we? :rotf:
            lines = text.splitlines()
            for i, line in enumerate(lines):
                if not line.lstrip(): continue
                assert len(line) >= dedent_chars, \
                    "line is shorter than detected minimum common indent (`dedent_chars`)??"
                if type is not None:
                    other_type = "\t" if type == " " else " "
                    for j in range(dedent_chars):
                        if line[j] == type:
                            continue
                        correct_name = "spaces" if type == " " else "tabs"
                        if line[j] == other_type:
                            wrong_name = "space(s)" if other_type == " " else "tab(s)"
                            e = ParseError(
                                f"Mixed indent: expected indent made of {correct_name}, found {wrong_name}",
                                (
                                    self.effective_file_name,
                                    start_pos[0] + i,
                                    start_pos[1] + j + 1, # Again 0-based so we make it 1-based
                                    line,
                                    start_pos[0] + i,
                                    start_pos[1] + j + 2
                                )
                            )
                            self.completely_propogate_parse_error = True
                            raise e
                        else:
                            e = ParseError(
                                f"Indent not enough: expected common indent of {dedent_chars} {correct_name}, "
                                #f"got {line[:dedent_chars]!r}",
                                f"got {j} {correct_name}",
                                (
                                    self.effective_file_name,
                                    start_pos[0] + i,
                                    start_pos[1] + 1, # Ditto
                                    line,
                                    start_pos[0] + i,
                                    start_pos[1] + j + 1
                                )
                            )
                            self.completely_propogate_parse_error = True
                            raise e
                lines[i] = line[dedent_chars:] #XXX: No reference alias problem?
            s = "\n".join(lines)
        else:
            # Transform back to original code.
            #
            # The reason we're not doing this:
            #
            #     s = _slice_line_col2(self._text, tokens[0].start, tokens[-1].end)
            #
            # is to keep compatible with (probably existing somewhere)
            # code like this, seen in python_v2.gram:
            #
            #     slice:
            #         # ...
            #         | a=named_expression {
            #             a
            #             if sys.version_info >= (3, 9) or isinstance(a, ast.Slice) else
            #             ast.Index(
            #                 value=a,
            #                 lineno=a.lineno,
            #                 col_offset=a.col_offset,
            #                 end_lineno=a.end_lineno,
            #                 end_col_offset=a.end_col_offset
            #             )
            #         }
            #
            # Note the action spans several lines.
            # - It is illegal to type it out in the REPL without adding brackets.
            # - Joining token texts with space `" ".join(map(lambda x: x.string, tokens))`
            #   is the legacy behavior.
            #   It *works* but looks *bad*, especially in this case,
            #   9 lines will become all on 1 line, it's harder to map an error location
            #   back to the original location.
            # - Adding brackets f"({THE_CODE})": Makes this invalid action
            #   get parsed as a generator expression, unexpectedly valid.
            #
            #       rule: a { x for x in a }
            #
            #   We could validate the action code with ast.parse, but it's problematic
            #   with respect to actions like `ast.Expr(..., LOCATIONS)`
            #   where the unsubstituted `LOCATIONS` causes the code to be invalid.
            #   Furthermore, I'd avoid the performance cost if possible.
            #   (but it's a possible future feature)
            # - _slice_line_col2 + .replace("\n", "\\\n"): Fails with triple strings.
            #   You'll have to manually parse tokens.
            # - _normalize_linecol + tokenize.untokenize fixes this issue by adding `\`:
            #
            #       return a\
            #       if sys.version_info >= (3, 9) or isinstance(a, ast.Slice) else\
            #       ast.Index(\
            #           value=a,\
            #           lineno=a.lineno,\
            #           col_offset=a.col_offset,\
            #           end_lineno=a.end_lineno,\
            #           end_col_offset=a.end_col_offset\
            #       )
            #
            #   Not ideal, but works best.
            #
            #   (Technically it's undefined behavior, but pegen has been using
            #   tokenize.tokenize all the time, so 🤷)
            #   (Avoiding the undefined behavior as said in the docs
            #   would require me to build my own tokenizer
            #   and that feels like a lot of effort
            #   and will be a breaking change)
            #   (Though I'm still at v0.x, breaking changes are okay? 😂)

            tokens = _normalize_linecol(tokens)
            s = tokenize.untokenize(tokens)
            if self._verbose: #XXX: ...
                import pickle
                print("  " * self._level + "## Normalized:", pickle.dumps(tokens))
        if self._verbose and is_stmts:
            print("  " * self._level + "## Parsed code:", repr(s))
        # TODO: Add a debug flag and clean debug printing around here
        #if "LOCATIONS" not in s and "UNREACHABLE" not in s and not is_stmts:
        #    ast.parse(s)
        return Action(s, is_stmts)

    # Temporary trick (plan to make it built-in)
    # TODO: Remove
    @logger
    def empty(self) -> RuleResult[None]:
        return None


# Keywords and soft keywords are listed at the end of the parser definition.
class GeneratedParser(Base):

    @memoize
    def r_start(self) -> RuleResult[Grammar]:
        # start: grammar $
        mark = self.mark()
        if (
            (grammar := (self.r_grammar())) is not FAILURE
            and
            (self.endmarker()) is not FAILURE
        ):
            return grammar
        self.reset(mark)
        return FAILURE

    @memoize
    def r_grammar(self) -> RuleResult[Grammar]:
        # grammar: meta* rule+ extern_decl*
        mark = self.mark()
        if (
            (metas := (self._loop0_1())) is not FAILURE
            and
            (rules := (self._loop1_2())) is not FAILURE
            and
            (extern_decls := (self._loop0_3())) is not FAILURE
        ):
            return Grammar(rules, extern_decls, metas)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_meta(self) -> RuleResult[MetaTuple]:
        # meta: "@" NAME NEWLINE | "@" NAME NAME NEWLINE | "@" NAME STRING NEWLINE
        mark = self.mark()
        if (
            (self.match_string("@")) is not FAILURE
            and
            (name := (self.name())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return (name.string, None)
        self.reset(mark)
        if (
            (self.match_string("@")) is not FAILURE
            and
            (a := (self.name())) is not FAILURE
            and
            (b := (self.name())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return (a.string, b.string)
        self.reset(mark)
        if (
            (self.match_string("@")) is not FAILURE
            and
            (name := (self.name())) is not FAILURE
            and
            (string := (self.string())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return (name.string, literal_eval(string.string))
        self.reset(mark)
        return FAILURE

    @memoize
    def r_rule(self) -> RuleResult[Rule]:
        # rule: rulename memoflag? ":" rule_rhs
        mark = self.mark()
        if (
            (rulename := (self.r_rulename())) is not FAILURE
            and
            (opt := (_temp if (_temp := (self.r_memoflag())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string(":")) is not FAILURE
            and
            (rule_rhs := (self.r_rule_rhs())) is not FAILURE
        ):
            return Rule(rulename[0], rulename[1], rule_rhs, memo=opt)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_extern_decl(self) -> RuleResult[ExternDecl]:
        # extern_decl: "extern" NAME annotation? NEWLINE
        mark = self.mark()
        if (
            (self.match_string("extern")) is not FAILURE
            and
            (name := (self.name())) is not FAILURE
            and
            (ann := (_temp if (_temp := (self.r_annotation())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return ExternDecl(name.string, ann or None)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_rulename(self) -> RuleResult[RuleName]:
        # rulename: NAME annotation?
        mark = self.mark()
        if (
            (name := (self.name())) is not FAILURE
            and
            (ann := (_temp if (_temp := (self.r_annotation())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return (name.string, ann or None)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_rule_rhs(self) -> RuleResult[Rhs]:
        # rule_rhs: NEWLINE INDENT alts NEWLINE DEDENT | alts? NEWLINE [(INDENT more_alts DEDENT)] | action NEWLINE | NEWLINE INDENT action NEWLINE DEDENT
        mark = self.mark()
        if (
            (self.newline()) is not FAILURE
            and
            (self.indent()) is not FAILURE
            and
            (alts := (self.r_alts())) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (self.dedent()) is not FAILURE
        ):
            return alts
        self.reset(mark)
        if (
            (alts := (_temp if (_temp := (self.r_alts())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (m := (_temp_1 if (_temp_1 := (self._tmp_4())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return Rhs((alts.alts if alts else []) + (m[1].alts if m else []))
        self.reset(mark)
        if (
            (action := (self.action())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            return Rhs([Alt([], action=action)])
        self.reset(mark)
        if (
            (self.newline()) is not FAILURE
            and
            (self.indent()) is not FAILURE
            and
            (action := (self.action())) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (self.dedent()) is not FAILURE
        ):
            return Rhs([Alt([], action=action)])
        self.reset(mark)
        return FAILURE

    @memoize
    def r_a(self) -> RuleResult[Any]:
        # a: 
        # nullable
        mark = self.mark()
        if True: # Empty branch
            return 1
        self.reset(mark)
        return FAILURE

    @memoize
    def r_memoflag(self) -> RuleResult[str]:
        # memoflag: '(' "memo" ')'
        mark = self.mark()
        if (
            (self.match_string('(')) is not FAILURE
            and
            (self.match_string("memo")) is not FAILURE
            and
            (self.match_string(')')) is not FAILURE
        ):
            return "memo"
        self.reset(mark)
        return FAILURE

    @memoize
    def r_alts(self) -> RuleResult[Rhs]:
        # alts: "|".alt+
        mark = self.mark()
        if (
            (alts := (self._gather_6())) is not FAILURE
        ):
            return Rhs(alts)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_more_alts(self) -> RuleResult[Rhs]:
        # more_alts: (("|" alt NEWLINE?))+
        mark = self.mark()
        if (
            (alts := (self._loop1_7())) is not FAILURE
        ):
            return Rhs(list(map(lambda x: x[1], alts)))
        self.reset(mark)
        return FAILURE

    @memoize
    def r_alt(self) -> RuleResult[Alt]:
        # alt: top_level_item+ '$'? action? | '$' action?
        mark = self.mark()
        if (
            (items := (self._loop1_8())) is not FAILURE
            and
            (e := (_temp if (_temp := (self.match_string('$'))) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (action := (_temp_1 if (_temp_1 := (self.action())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return Alt(items + [TopLevelItem(None, NameLeaf('ENDMARKER'))] if e else items, action=action or None)
        self.reset(mark)
        if (
            (self.match_string('$')) is not FAILURE
            and
            (action := (_temp if (_temp := (self.action())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return Alt([TopLevelItem(None, NameLeaf('ENDMARKER'))], action=action or None)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_top_level_item(self) -> RuleResult[TopLevelItem]:
        # top_level_item: NAME annotation '=' ~ item | NAME '=' ~ item | item | top_level_others
        mark = self.mark()
        __cut = False
        if (
            (name := (self.name())) is not FAILURE
            and
            (annotation := (self.r_annotation())) is not FAILURE
            and
            (self.match_string('=')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (item := (self.r_item())) is not FAILURE
        ):
            return TopLevelItem(name.string, item, annotation)
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (name := (self.name())) is not FAILURE
            and
            (self.match_string('=')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (item := (self.r_item())) is not FAILURE
        ):
            return TopLevelItem(name.string, item)
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (item := (self.r_item())) is not FAILURE
        ):
            return TopLevelItem(None, item)
        self.reset(mark)
        if (
            (it := (self.r_top_level_others())) is not FAILURE
        ):
            return TopLevelItem(None, it)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_top_level_others(self) -> RuleResult[LookaheadOrCut]:
        # top_level_others: '&' '&' ~ atom | '&' ~ atom | '!' ~ atom | '~'
        mark = self.mark()
        __cut = False
        if (
            (self.match_string('&')) is not FAILURE
            and
            (self.match_string('&')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atom := (self.r_atom())) is not FAILURE
        ):
            return Forced(atom)
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (self.match_string('&')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atom := (self.r_atom())) is not FAILURE
        ):
            return PositiveLookahead(atom)
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (self.match_string('!')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atom := (self.r_atom())) is not FAILURE
        ):
            return NegativeLookahead(atom)
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (self.match_string('~')) is not FAILURE
        ):
            return Cut()
        self.reset(mark)
        return FAILURE

    @memoize
    def r_item(self) -> RuleResult[Item]:
        # item: '[' ~ alts ']' | atom '?' | atom '*' | atom '+' | atom '.' atom '+' | atom
        mark = self.mark()
        __cut = False
        if (
            (self.match_string('[')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (alts := (self.r_alts())) is not FAILURE
            and
            (self.match_string(']')) is not FAILURE
        ):
            return Opt(Group(alts))
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (atom := (self.r_atom())) is not FAILURE
            and
            (self.match_string('?')) is not FAILURE
        ):
            return Opt(atom)
        self.reset(mark)
        if (
            (atom := (self.r_atom())) is not FAILURE
            and
            (self.match_string('*')) is not FAILURE
        ):
            return Repeat0(atom)
        self.reset(mark)
        if (
            (atom := (self.r_atom())) is not FAILURE
            and
            (self.match_string('+')) is not FAILURE
        ):
            return Repeat1(atom)
        self.reset(mark)
        if (
            (sep := (self.r_atom())) is not FAILURE
            and
            (self.match_string('.')) is not FAILURE
            and
            (node := (self.r_atom())) is not FAILURE
            and
            (self.match_string('+')) is not FAILURE
        ):
            return Gather(sep, node)
        self.reset(mark)
        if (
            (atom := (self.r_atom())) is not FAILURE
        ):
            return atom
        self.reset(mark)
        return FAILURE

    @memoize
    def r_atom(self) -> RuleResult[Plain]:
        # atom: '(' ~ alts ')' | NAME | STRING
        mark = self.mark()
        __cut = False
        if (
            (self.match_string('(')) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (alts := (self.r_alts())) is not FAILURE
            and
            (self.match_string(')')) is not FAILURE
        ):
            return Group(alts)
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (name := (self.name())) is not FAILURE
        ):
            return NameLeaf(name.string)
        self.reset(mark)
        if (
            (string := (self.string())) is not FAILURE
        ):
            return StringLeaf(string.string)
        self.reset(mark)
        return FAILURE

    @memoize
    def r_annotation(self) -> RuleResult[str]:
        # annotation: "[" ~ target_atoms "]"
        mark = self.mark()
        __cut = False
        if (
            (self.match_string("[")) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (target_atoms := (self.r_target_atoms())) is not FAILURE
            and
            (self.match_string("]")) is not FAILURE
        ):
            return target_atoms
        self.reset(mark)
        if __cut:
            return FAILURE
        return FAILURE

    @memoize
    def r_target_atoms(self) -> RuleResult[str]:
        # target_atoms: target_atom target_atoms | target_atom
        mark = self.mark()
        if (
            (target_atom := (self.r_target_atom())) is not FAILURE
            and
            (target_atoms := (self.r_target_atoms())) is not FAILURE
        ):
            return target_atom + " " + target_atoms
        self.reset(mark)
        if (
            (target_atom := (self.r_target_atom())) is not FAILURE
        ):
            return target_atom
        self.reset(mark)
        return FAILURE

    @memoize
    def r_target_atom(self) -> RuleResult[str]:
        # target_atom: "{" ~ target_atoms? "}" | "[" ~ target_atoms? "]" | NAME "*" | NAME | NUMBER | STRING | FSTRING_START target_fstring_middle* FSTRING_END | "?" | ":" | !"}" !"]" OP
        mark = self.mark()
        __cut = False
        if (
            (self.match_string("{")) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atoms := (_temp if (_temp := (self.r_target_atoms())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string("}")) is not FAILURE
        ):
            return "{" + (atoms or "") + "}"
        self.reset(mark)
        if __cut:
            return FAILURE
        __cut = False
        if (
            (self.match_string("[")) is not FAILURE
            and
            (__cut := (None) is not FAILURE)
            and
            (atoms := (_temp if (_temp := (self.r_target_atoms())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string("]")) is not FAILURE
        ):
            return "[" + (atoms or "") + "]"
        self.reset(mark)
        if __cut:
            return FAILURE
        if (
            (name := (self.name())) is not FAILURE
            and
            (self.match_string("*")) is not FAILURE
        ):
            return name.string + "*"
        self.reset(mark)
        if (
            (name := (self.name())) is not FAILURE
        ):
            return name.string
        self.reset(mark)
        if (
            (number := (self.number())) is not FAILURE
        ):
            return number.string
        self.reset(mark)
        if (
            (string := (self.string())) is not FAILURE
        ):
            return string.string
        self.reset(mark)
        if (
            (l := (self.fstring_start())) is not FAILURE
            and
            (m := (self._loop0_9())) is not FAILURE
            and
            (r := (self.fstring_end())) is not FAILURE
        ):
            return l.string + "".join(m) + r.string
        self.reset(mark)
        if (
            (self.match_string("?")) is not FAILURE
        ):
            return "?"
        self.reset(mark)
        if (
            (self.match_string(":")) is not FAILURE
        ):
            return ":"
        self.reset(mark)
        if (
            (self.negative_lookahead(self.match_string, "}")) is not FAILURE
            and
            (self.negative_lookahead(self.match_string, "]")) is not FAILURE
            and
            (op := (self.op())) is not FAILURE
        ):
            return op.string
        self.reset(mark)
        return FAILURE

    @memoize
    def r_target_fstring_middle(self) -> RuleResult[str]:
        # target_fstring_middle: FSTRING_MIDDLE | "{" | "}" | target_atom
        mark = self.mark()
        if (
            (fstring_middle := (self.fstring_middle())) is not FAILURE
        ):
            return fstring_middle.string
        self.reset(mark)
        if (
            (self.match_string("{")) is not FAILURE
        ):
            return "{"
        self.reset(mark)
        if (
            (self.match_string("}")) is not FAILURE
        ):
            return "}"
        self.reset(mark)
        if (
            (target_atom := (self.r_target_atom())) is not FAILURE
        ):
            return target_atom
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop0_1(self) -> RuleResult[Any]:
        # _loop0_1: meta
        mark = self.mark()
        children = []
        while (
            (meta := (self.r_meta())) is not FAILURE
        ):
            children.append(meta)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _loop1_2(self) -> RuleResult[Any]:
        # _loop1_2: rule
        mark = self.mark()
        children = []
        while (
            (rule := (self.r_rule())) is not FAILURE
        ):
            children.append(rule)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop0_3(self) -> RuleResult[Any]:
        # _loop0_3: extern_decl
        mark = self.mark()
        children = []
        while (
            (extern_decl := (self.r_extern_decl())) is not FAILURE
        ):
            children.append(extern_decl)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _tmp_4(self) -> RuleResult[Any]:
        # _tmp_4: INDENT more_alts DEDENT
        mark = self.mark()
        if (
            (indent := (self.indent())) is not FAILURE
            and
            (more_alts := (self.r_more_alts())) is not FAILURE
            and
            (dedent := (self.dedent())) is not FAILURE
        ):
            return [indent, more_alts, dedent]
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop0_5(self) -> RuleResult[Any]:
        # _loop0_5: "|" alt
        mark = self.mark()
        children = []
        while (
            (self.match_string("|")) is not FAILURE
            and
            (elem := (self.r_alt())) is not FAILURE
        ):
            children.append(elem)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _gather_6(self) -> RuleResult[Any]:
        # _gather_6: alt _loop0_5
        mark = self.mark()
        if (
            (elem := (self.r_alt())) is not FAILURE
            and
            (seq := (self._loop0_5())) is not FAILURE
        ):
            return [elem] + seq
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop1_7(self) -> RuleResult[Any]:
        # _loop1_7: ("|" alt NEWLINE?)
        mark = self.mark()
        children = []
        while (
            (_tmp_10 := (self._tmp_10())) is not FAILURE
        ):
            children.append(_tmp_10)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop1_8(self) -> RuleResult[Any]:
        # _loop1_8: top_level_item
        mark = self.mark()
        children = []
        while (
            (top_level_item := (self.r_top_level_item())) is not FAILURE
        ):
            children.append(top_level_item)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop0_9(self) -> RuleResult[Any]:
        # _loop0_9: target_fstring_middle
        mark = self.mark()
        children = []
        while (
            (target_fstring_middle := (self.r_target_fstring_middle())) is not FAILURE
        ):
            children.append(target_fstring_middle)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _tmp_10(self) -> RuleResult[Any]:
        # _tmp_10: "|" alt NEWLINE?
        mark = self.mark()
        if (
            (__literal := (self.match_string("|"))) is not FAILURE
            and
            (alt := (self.r_alt())) is not FAILURE
            and
            (opt := (_temp if (_temp := (self.newline())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            return [__literal, alt, opt]
        self.reset(mark)
        return FAILURE

    def start(self) -> Union[Grammar, ParseFailure]:
        try:
            value = self.r_start()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def grammar(self) -> Union[Grammar, ParseFailure]:
        try:
            value = self.r_grammar()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def meta(self) -> Union[MetaTuple, ParseFailure]:
        try:
            value = self.r_meta()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def rule(self) -> Union[Rule, ParseFailure]:
        try:
            value = self.r_rule()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def extern_decl(self) -> Union[ExternDecl, ParseFailure]:
        try:
            value = self.r_extern_decl()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def rulename(self) -> Union[RuleName, ParseFailure]:
        try:
            value = self.r_rulename()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def rule_rhs(self) -> Union[Rhs, ParseFailure]:
        try:
            value = self.r_rule_rhs()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def a(self) -> Union[None, ParseFailure]:
        try:
            value = self.r_a()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def memoflag(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_memoflag()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def alts(self) -> Union[Rhs, ParseFailure]:
        try:
            value = self.r_alts()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def more_alts(self) -> Union[Rhs, ParseFailure]:
        try:
            value = self.r_more_alts()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def alt(self) -> Union[Alt, ParseFailure]:
        try:
            value = self.r_alt()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def top_level_item(self) -> Union[TopLevelItem, ParseFailure]:
        try:
            value = self.r_top_level_item()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def top_level_others(self) -> Union[LookaheadOrCut, ParseFailure]:
        try:
            value = self.r_top_level_others()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def item(self) -> Union[Item, ParseFailure]:
        try:
            value = self.r_item()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def atom(self) -> Union[Plain, ParseFailure]:
        try:
            value = self.r_atom()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def annotation(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_annotation()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def target_atoms(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_target_atoms()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def target_atom(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_target_atom()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    def target_fstring_middle(self) -> Union[str, ParseFailure]:
        try:
            value = self.r_target_fstring_middle()
            return ParseFailure.from_general_failure(self.diagnose(), None) if value is FAILURE else value
        except ParseError as e:
            return ParseFailure.from_raised_failure(e)

    KEYWORDS = ()
    SOFT_KEYWORDS = ('extern', 'memo')


if __name__ == '__main__':
    from stde.pegen.v2.parser import simple_parser_main
    simple_parser_main(GeneratedParser)
