#!/usr/bin/env python
# @generated by stde.pegen from src/stde/pegen/v2/metagrammar.gram

from typing import Any, Optional
from stde.pegen.v2.parser import (
    memoize, memoize_left_rec, logger, DefaultParser, CharBasedParser,
    RuleResult, ResultFlag, NO_MATCH, FAILURE)
#from stde.pegen.v2.parser_old import memoize, memoize_left_rec, logger, DefaultParser, CharBasedParser #type:ignore
from ast import literal_eval
from typing import List, Union, Iterable
import token
import tokenize
from tokenize import TokenInfo

FAILURE = ResultFlag.FAILURE

from stde.pegen.v2.grammar import (
    Alt,
    #Action,
    GrammarItem,
    Cut,
    ExternDecl,
    Forced,
    Gather,
    Group,
    Item,
    Lookahead,
    LookaheadOrCut,
    MetaTuple,
    NameLeaf,
    TopLevelItem,
    NegativeLookahead,
    Opt,
    Plain,
    PositiveLookahead,
    Repeat0,
    Repeat1,
    Rhs,
    Rule,
    RuleName,
    Grammar,
    StringLeaf,
)

#TODO: Blocks (having its own return) vs. expressions
def _normalize_linecol(tokens: List[TokenInfo]) -> List[TokenInfo]:
    if not tokens:
        return []
    # first token has line 1
    first_line = tokens[0].start[0]
    line_subtract = tokens[0].start[0] - 1  # Start with line 1
    column_subtract = tokens[0].start[1]  # Start with column 0
    def replace(t: TokenInfo) -> TokenInfo:
        if t.start[0] == first_line:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1] - column_subtract),
                              end=(t.end[0] - line_subtract, t.end[1] - column_subtract))
        else:
            return t._replace(start=(t.start[0] - line_subtract, t.start[1]),
                              end=(t.end[0] - line_subtract, t.end[1]))
    return list(map(replace, tokens))


class Base(DefaultParser):
    @memoize
    def action_contents(self) -> RuleResult[str]:
        """Note: The result should be parsable by ast.parse."""
        m = self.mark()
        level = 1
        has_return_stmt = False
        tokens = []
        prevmark = m
        while True:
            t = self._tokenizer.peek()
            if t.type == token.ENDMARKER:
                self.reset(m)
                return FAILURE
            self._tokenizer.getnext()
            if t.string == "}":
                level -= 1
                if level == 0:
                    break
            tokens.append(t)
            if t.string == "{":
                level += 1
            elif t.string == "return":
                has_return_stmt = True
            prevmark = self.mark()
        self.reset(prevmark) # Don't consume the last right brace
        tokens = _normalize_linecol(tokens)
        s = tokenize.untokenize(tokens)
        if self._verbose: #XXX: ...
            print("  " * self._level + "## Parsed code:", repr(s))
        return s

def _rhs_from_alts_s(alts_s: Iterable[Rhs]) -> Rhs:
    all_alts: List[Alt] = []
    for alts in alts_s:
        all_alts.extend(alts.alts)
    return Rhs(all_alts)

# Keywords and soft keywords are listed at the end of the parser definition.
class GeneratedParser(Base):

    @memoize
    def start(self) -> RuleResult[Grammar]:
        # start: grammar $
        mark = self.mark()
        if (
            (r_grammar := (self.grammar())) is not FAILURE
            and
            (self.endmarker()) is not FAILURE
        ):
            grammar = r_grammar
            return grammar
        self.reset(mark)
        return FAILURE

    @memoize
    def grammar(self) -> RuleResult[Grammar]:
        # grammar: meta* rule+ extern_decl*
        mark = self.mark()
        if (
            (r_metas := (self._loop0_1())) is not FAILURE
            and
            (r_rules := (self._loop1_2())) is not FAILURE
            and
            (r_extern_decls := (self._loop0_3())) is not FAILURE
        ):
            metas = r_metas
            rules = r_rules
            extern_decls = r_extern_decls
            return Grammar(rules, extern_decls, metas)
        self.reset(mark)
        return FAILURE

    @memoize
    def meta(self) -> RuleResult[MetaTuple]:
        # meta: "@" NAME NEWLINE | "@" NAME NAME NEWLINE | "@" NAME STRING NEWLINE
        mark = self.mark()
        if (
            (self.match_string("@")) is not FAILURE
            and
            (r_name := (self.name())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            name = r_name
            return (name.string, None)
        self.reset(mark)
        if (
            (self.match_string("@")) is not FAILURE
            and
            (r_a := (self.name())) is not FAILURE
            and
            (r_b := (self.name())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            a = r_a
            b = r_b
            return (a.string, b.string)
        self.reset(mark)
        if (
            (self.match_string("@")) is not FAILURE
            and
            (r_name := (self.name())) is not FAILURE
            and
            (r_string := (self.string())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            name = r_name
            string = r_string
            return (name.string, literal_eval(string.string))
        self.reset(mark)
        return FAILURE

    @memoize
    def rule(self) -> RuleResult[Rule]:
        # rule: rulename memoflag? ":" rule_rhs
        mark = self.mark()
        if (
            (r_rulename := (self.rulename())) is not FAILURE
            and
            (r_opt := (_temp if (_temp := (self.memoflag())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string(":")) is not FAILURE
            and
            (r_rule_rhs := (self.rule_rhs())) is not FAILURE
        ):
            rulename = r_rulename
            opt = r_opt
            rule_rhs = r_rule_rhs
            return Rule(rulename[0], rulename[1], rule_rhs, memo=opt)
        self.reset(mark)
        return FAILURE

    @memoize
    def extern_decl(self) -> RuleResult[ExternDecl]:
        # extern_decl: "extern" NAME annotation? NEWLINE
        mark = self.mark()
        if (
            (self.match_string("extern")) is not FAILURE
            and
            (r_name := (self.name())) is not FAILURE
            and
            (r_ann := (_temp if (_temp := (self.annotation())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            name = r_name
            ann = r_ann
            return ExternDecl(name.string, ann or None)
        self.reset(mark)
        return FAILURE

    @memoize
    def rulename(self) -> RuleResult[RuleName]:
        # rulename: NAME annotation | NAME
        mark = self.mark()
        if (
            (r_name := (self.name())) is not FAILURE
            and
            (r_annotation := (self.annotation())) is not FAILURE
        ):
            name = r_name
            annotation = r_annotation
            return (name.string, annotation)
        self.reset(mark)
        if (
            (r_name := (self.name())) is not FAILURE
        ):
            name = r_name
            return (name.string, None)
        self.reset(mark)
        return FAILURE

    @memoize
    def rule_rhs(self) -> RuleResult[Rhs]:
        # rule_rhs: alts? NEWLINE INDENT more_alts DEDENT | NEWLINE INDENT alts NEWLINE DEDENT | alts NEWLINE
        mark = self.mark()
        if (
            (r_alts := (_temp if (_temp := (self.alts())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (self.indent()) is not FAILURE
            and
            (r_more_alts := (self.more_alts())) is not FAILURE
            and
            (self.dedent()) is not FAILURE
        ):
            alts = r_alts
            more_alts = r_more_alts
            return Rhs(alts.alts + more_alts.alts) if alts else more_alts
        self.reset(mark)
        if (
            (self.newline()) is not FAILURE
            and
            (self.indent()) is not FAILURE
            and
            (r_alts := (self.alts())) is not FAILURE
            and
            (self.newline()) is not FAILURE
            and
            (self.dedent()) is not FAILURE
        ):
            alts = r_alts
            return alts
        self.reset(mark)
        if (
            (r_alts := (self.alts())) is not FAILURE
            and
            (self.newline()) is not FAILURE
        ):
            alts = r_alts
            return alts
        self.reset(mark)
        return FAILURE

    @memoize
    def memoflag(self) -> RuleResult[str]:
        # memoflag: '(' "memo" ')'
        mark = self.mark()
        if (
            (self.match_string('(')) is not FAILURE
            and
            (self.match_string("memo")) is not FAILURE
            and
            (self.match_string(')')) is not FAILURE
        ):
            return "memo"
        self.reset(mark)
        return FAILURE

    @memoize
    def alts(self) -> RuleResult[Rhs]:
        # alts: "|".alt+
        mark = self.mark()
        if (
            (r_alts := (self._gather_4())) is not FAILURE
        ):
            alts = r_alts
            return Rhs(alts)
        self.reset(mark)
        return FAILURE

    @memoize
    def more_alts(self) -> RuleResult[Rhs]:
        # more_alts: (("|" alts NEWLINE))+
        mark = self.mark()
        if (
            (r_alts_s := (self._loop1_6())) is not FAILURE
        ):
            alts_s = r_alts_s
            return _rhs_from_alts_s(map(lambda x: x[1], alts_s))
        self.reset(mark)
        return FAILURE

    @memoize
    def alt(self) -> RuleResult[Alt]:
        # alt: items '$'? action?
        mark = self.mark()
        if (
            (r_items := (self.items())) is not FAILURE
            and
            (r_e := (_temp if (_temp := (self.match_string('$'))) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (r_action := (_temp_1 if (_temp_1 := (self.action())) is not FAILURE else NO_MATCH)) is not FAILURE
        ):
            items = r_items
            e = r_e
            action = r_action
            return Alt(items + [TopLevelItem(None, NameLeaf('ENDMARKER'))] if e else items, action=action)
        self.reset(mark)
        return FAILURE

    @memoize
    def items(self) -> RuleResult[List [TopLevelItem]]:
        # items: top_level_item+
        mark = self.mark()
        if (
            (r__loop1_7 := (self._loop1_7())) is not FAILURE
        ):
            _loop1_7 = r__loop1_7
            return _loop1_7
        self.reset(mark)
        return FAILURE

    @memoize
    def top_level_item(self) -> RuleResult[TopLevelItem]:
        # top_level_item: NAME annotation '=' ~ item | NAME '=' ~ item | item | top_level_others
        mark = self.mark()
        cut = False
        if (
            (r_name := (self.name())) is not FAILURE
            and
            (r_annotation := (self.annotation())) is not FAILURE
            and
            (self.match_string('=')) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_item := (self.item())) is not FAILURE
        ):
            name = r_name
            annotation = r_annotation
            item = r_item
            return TopLevelItem(name.string, item, annotation)
        self.reset(mark)
        if cut:
            return FAILURE
        cut = False
        if (
            (r_name := (self.name())) is not FAILURE
            and
            (self.match_string('=')) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_item := (self.item())) is not FAILURE
        ):
            name = r_name
            item = r_item
            return TopLevelItem(name.string, item)
        self.reset(mark)
        if cut:
            return FAILURE
        if (
            (r_item := (self.item())) is not FAILURE
        ):
            item = r_item
            return TopLevelItem(None, item)
        self.reset(mark)
        if (
            (r_it := (self.top_level_others())) is not FAILURE
        ):
            it = r_it
            return TopLevelItem(None, it)
        self.reset(mark)
        return FAILURE

    @memoize
    def top_level_others(self) -> RuleResult[LookaheadOrCut]:
        # top_level_others: '&' '&' ~ atom | '&' ~ atom | '!' ~ atom | '~'
        mark = self.mark()
        cut = False
        if (
            (self.match_string('&')) is not FAILURE
            and
            (self.match_string('&')) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_atom := (self.atom())) is not FAILURE
        ):
            atom = r_atom
            return Forced(atom)
        self.reset(mark)
        if cut:
            return FAILURE
        cut = False
        if (
            (self.match_string('&')) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_atom := (self.atom())) is not FAILURE
        ):
            atom = r_atom
            return PositiveLookahead(atom)
        self.reset(mark)
        if cut:
            return FAILURE
        cut = False
        if (
            (self.match_string('!')) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_atom := (self.atom())) is not FAILURE
        ):
            atom = r_atom
            return NegativeLookahead(atom)
        self.reset(mark)
        if cut:
            return FAILURE
        if (
            (self.match_string('~')) is not FAILURE
        ):
            return Cut()
        self.reset(mark)
        return FAILURE

    @memoize
    def item(self) -> RuleResult[Item]:
        # item: '[' ~ alts ']' | atom '?' | atom '*' | atom '+' | atom '.' atom '+' | atom
        mark = self.mark()
        cut = False
        if (
            (self.match_string('[')) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_alts := (self.alts())) is not FAILURE
            and
            (self.match_string(']')) is not FAILURE
        ):
            alts = r_alts
            return Opt(Group(alts))
        self.reset(mark)
        if cut:
            return FAILURE
        if (
            (r_atom := (self.atom())) is not FAILURE
            and
            (self.match_string('?')) is not FAILURE
        ):
            atom = r_atom
            return Opt(atom)
        self.reset(mark)
        if (
            (r_atom := (self.atom())) is not FAILURE
            and
            (self.match_string('*')) is not FAILURE
        ):
            atom = r_atom
            return Repeat0(atom)
        self.reset(mark)
        if (
            (r_atom := (self.atom())) is not FAILURE
            and
            (self.match_string('+')) is not FAILURE
        ):
            atom = r_atom
            return Repeat1(atom)
        self.reset(mark)
        if (
            (r_sep := (self.atom())) is not FAILURE
            and
            (self.match_string('.')) is not FAILURE
            and
            (r_node := (self.atom())) is not FAILURE
            and
            (self.match_string('+')) is not FAILURE
        ):
            sep = r_sep
            node = r_node
            return Gather(sep, node)
        self.reset(mark)
        if (
            (r_atom := (self.atom())) is not FAILURE
        ):
            atom = r_atom
            return atom
        self.reset(mark)
        return FAILURE

    @memoize
    def atom(self) -> RuleResult[Plain]:
        # atom: '(' ~ alts ')' | NAME | STRING
        mark = self.mark()
        cut = False
        if (
            (self.match_string('(')) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_alts := (self.alts())) is not FAILURE
            and
            (self.match_string(')')) is not FAILURE
        ):
            alts = r_alts
            return Group(alts)
        self.reset(mark)
        if cut:
            return FAILURE
        if (
            (r_name := (self.name())) is not FAILURE
        ):
            name = r_name
            return NameLeaf(name.string)
        self.reset(mark)
        if (
            (r_string := (self.string())) is not FAILURE
        ):
            string = r_string
            return StringLeaf(string.string)
        self.reset(mark)
        return FAILURE

    @memoize
    def action(self) -> RuleResult[str]:
        # action: "{" ~ action_contents "}"
        mark = self.mark()
        cut = False
        if (
            (self.match_string("{")) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_action_contents := (self.action_contents())) is not FAILURE
            and
            (self.match_string("}")) is not FAILURE
        ):
            action_contents = r_action_contents
            return action_contents
        self.reset(mark)
        if cut:
            return FAILURE
        return FAILURE

    @memoize
    def annotation(self) -> RuleResult[str]:
        # annotation: "[" ~ target_atoms "]"
        mark = self.mark()
        cut = False
        if (
            (self.match_string("[")) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_target_atoms := (self.target_atoms())) is not FAILURE
            and
            (self.match_string("]")) is not FAILURE
        ):
            target_atoms = r_target_atoms
            return target_atoms
        self.reset(mark)
        if cut:
            return FAILURE
        return FAILURE

    @memoize
    def target_atoms(self) -> RuleResult[str]:
        # target_atoms: target_atom target_atoms | target_atom
        mark = self.mark()
        if (
            (r_target_atom := (self.target_atom())) is not FAILURE
            and
            (r_target_atoms := (self.target_atoms())) is not FAILURE
        ):
            target_atom = r_target_atom
            target_atoms = r_target_atoms
            return target_atom + " " + target_atoms
        self.reset(mark)
        if (
            (r_target_atom := (self.target_atom())) is not FAILURE
        ):
            target_atom = r_target_atom
            return target_atom
        self.reset(mark)
        return FAILURE

    @memoize
    def target_atom(self) -> RuleResult[str]:
        # target_atom: "{" ~ target_atoms? "}" | "[" ~ target_atoms? "]" | NAME "*" | NAME | NUMBER | STRING | FSTRING_START target_fstring_middle* FSTRING_END | "?" | ":" | !"}" !"]" OP
        mark = self.mark()
        cut = False
        if (
            (self.match_string("{")) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_atoms := (_temp if (_temp := (self.target_atoms())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string("}")) is not FAILURE
        ):
            atoms = r_atoms
            return "{" + (atoms or "") + "}"
        self.reset(mark)
        if cut:
            return FAILURE
        cut = False
        if (
            (self.match_string("[")) is not FAILURE
            and
            (cut := (None) is not FAILURE)
            and
            (r_atoms := (_temp if (_temp := (self.target_atoms())) is not FAILURE else NO_MATCH)) is not FAILURE
            and
            (self.match_string("]")) is not FAILURE
        ):
            atoms = r_atoms
            return "[" + (atoms or "") + "]"
        self.reset(mark)
        if cut:
            return FAILURE
        if (
            (r_name := (self.name())) is not FAILURE
            and
            (self.match_string("*")) is not FAILURE
        ):
            name = r_name
            return name.string + "*"
        self.reset(mark)
        if (
            (r_name := (self.name())) is not FAILURE
        ):
            name = r_name
            return name.string
        self.reset(mark)
        if (
            (r_number := (self.number())) is not FAILURE
        ):
            number = r_number
            return number.string
        self.reset(mark)
        if (
            (r_string := (self.string())) is not FAILURE
        ):
            string = r_string
            return string.string
        self.reset(mark)
        if (
            (r_l := (self.fstring_start())) is not FAILURE
            and
            (r_m := (self._loop0_8())) is not FAILURE
            and
            (r_r := (self.fstring_end())) is not FAILURE
        ):
            l = r_l
            m = r_m
            r = r_r
            return l.string + "".join(m) + r.string
        self.reset(mark)
        if (
            (self.match_string("?")) is not FAILURE
        ):
            return "?"
        self.reset(mark)
        if (
            (self.match_string(":")) is not FAILURE
        ):
            return ":"
        self.reset(mark)
        if (
            (self.negative_lookahead(self.match_string, "}")) is not FAILURE
            and
            (self.negative_lookahead(self.match_string, "]")) is not FAILURE
            and
            (r_op := (self.op())) is not FAILURE
        ):
            op = r_op
            return op.string
        self.reset(mark)
        return FAILURE

    @memoize
    def target_fstring_middle(self) -> RuleResult[str]:
        # target_fstring_middle: FSTRING_MIDDLE | "{" | "}" | target_atom
        mark = self.mark()
        if (
            (r_fstring_middle := (self.fstring_middle())) is not FAILURE
        ):
            fstring_middle = r_fstring_middle
            return fstring_middle.string
        self.reset(mark)
        if (
            (self.match_string("{")) is not FAILURE
        ):
            return "{"
        self.reset(mark)
        if (
            (self.match_string("}")) is not FAILURE
        ):
            return "}"
        self.reset(mark)
        if (
            (r_target_atom := (self.target_atom())) is not FAILURE
        ):
            target_atom = r_target_atom
            return target_atom
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop0_1(self) -> RuleResult[Any]:
        # _loop0_1: meta
        mark = self.mark()
        children = []
        while (
            (r_meta := (self.meta())) is not FAILURE
        ):
            meta = r_meta
            children.append(meta)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _loop1_2(self) -> RuleResult[Any]:
        # _loop1_2: rule
        mark = self.mark()
        children = []
        while (
            (r_rule := (self.rule())) is not FAILURE
        ):
            rule = r_rule
            children.append(rule)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop0_3(self) -> RuleResult[Any]:
        # _loop0_3: extern_decl
        mark = self.mark()
        children = []
        while (
            (r_extern_decl := (self.extern_decl())) is not FAILURE
        ):
            extern_decl = r_extern_decl
            children.append(extern_decl)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _loop0_5(self) -> RuleResult[Any]:
        # _loop0_5: "|" alt
        mark = self.mark()
        children = []
        while (
            (self.match_string("|")) is not FAILURE
            and
            (r_elem := (self.alt())) is not FAILURE
        ):
            elem = r_elem
            children.append(elem)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _gather_4(self) -> RuleResult[Any]:
        # _gather_4: alt _loop0_5
        mark = self.mark()
        if (
            (r_elem := (self.alt())) is not FAILURE
            is not None
            and
            (r_seq := (self._loop0_5())) is not FAILURE
            is not None
        ):
            elem = r_elem
            seq = r_seq
            return [elem] + seq
        self.reset(mark)
        return FAILURE

    @memoize
    def _loop1_6(self) -> RuleResult[Any]:
        # _loop1_6: ("|" alts NEWLINE)
        mark = self.mark()
        children = []
        while (
            (r__tmp_9 := (self._tmp_9())) is not FAILURE
        ):
            _tmp_9 = r__tmp_9
            children.append(_tmp_9)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop1_7(self) -> RuleResult[Any]:
        # _loop1_7: top_level_item
        mark = self.mark()
        children = []
        while (
            (r_top_level_item := (self.top_level_item())) is not FAILURE
        ):
            top_level_item = r_top_level_item
            children.append(top_level_item)
            mark = self.mark()
        self.reset(mark)
        return children or ResultFlag.FAILURE

    @memoize
    def _loop0_8(self) -> RuleResult[Any]:
        # _loop0_8: target_fstring_middle
        mark = self.mark()
        children = []
        while (
            (r_target_fstring_middle := (self.target_fstring_middle())) is not FAILURE
        ):
            target_fstring_middle = r_target_fstring_middle
            children.append(target_fstring_middle)
            mark = self.mark()
        self.reset(mark)
        return children

    @memoize
    def _tmp_9(self) -> RuleResult[Any]:
        # _tmp_9: "|" alts NEWLINE
        mark = self.mark()
        if (
            (r_literal := (self.match_string("|"))) is not FAILURE
            and
            (r_alts := (self.alts())) is not FAILURE
            and
            (r_newline := (self.newline())) is not FAILURE
        ):
            literal = r_literal
            alts = r_alts
            newline = r_newline
            return [literal, alts, newline]
        self.reset(mark)
        return FAILURE

    KEYWORDS = ()
    SOFT_KEYWORDS = ('extern', 'memo')


if __name__ == '__main__':
    from stde.pegen.v2.parser import simple_parser_main
    simple_parser_main(GeneratedParser)
